apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
spec:
  selector:
    app: usermgmnt
  ports:
    - name: usermgmt-port
      port: 8095
      targetPort: 8095
      nodePort: 31231
  type: NodePort
