apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      createdBy: SantoshPusparaj
  template:
    metadata:
      name: webapps
      labels:
        createdBy: SantoshPusparaj
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
